name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: alpine:3.15
    strategy:
      matrix:
        model: ["TS80P"]
      fail-fast: true
    steps:
      - name: Install dependencies (apk)
        run: apk add --no-cache gcc-arm-none-eabi newlib-arm-none-eabi findutils make git python3 py3-pip

      - name: Install dependencies (py)
        run: pip3 install IntelHex

      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: prep
        run: mkdir -p /tmp/${{ matrix.model }}

      - name: build runtime ${{ matrix.model }}
        run: make all build_type=runtime model=${{ matrix.model }}

      - name: cp outputs
        run: cp build/*.hex build/*.dfu /tmp/${{ matrix.model }}

      - name: build bootloader ${{ matrix.model }}
        run: make clean && make all build_type=bootloader model=${{ matrix.model }}

      - name: cp outputs
        run: cp build/*.hex build/*.dfu /tmp/${{ matrix.model }}

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.model }}
          path: |
            /tmp/${{ matrix.model }}/*.hex
            /tmp/${{ matrix.model }}/*.dfu
          if-no-files-found: error
